name: copilot-acp-server

services:
  copilot-acp:
    build: .
    image: robkaandorp/copilot-acp-server:dev
    container_name: copilot-acp
    ports:
      - "8000:8000"
    volumes:
      - "${COPILOT_SANDBOX:-./sandbox}/home:/copilot-home"
      - "${COPILOT_SANDBOX:-./sandbox}/.copilot:/root/.copilot"
    working_dir: /copilot-home
    env_file:
      - path: ./default.env
        required: true
      - path: ./.env
        required: false
